[project]
name = "plc-platform-backend"
version = "0.1.0"
description = ""
authors = [{ name = "filippodaniotti", email = "febbrosto@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11,<3.12"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
fastapi = { version = ">=0.115.6,<0.116.0", extras = ["standard"] }
uvicorn = { version = ">=0.34.0,<0.35.0" }
plctestbench = { path = "../plc-testbench", develop = true }
pydantic-settings = "^2.7.1"
motor = "^3.7.0"
dramatiq = { extras = ["redis"], version = "^1.18.0" }


[tool.poetry.group.dev.dependencies]
debugpy = "^1.8.11"
